import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Navbar from '../components/Navbar'
import Head from "next/head"
import { Analytics } from '@vercel/analytics/react';


export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className='	sb_center'>
      <Analytics />
      <Head>
        <title>Sunny Jayaram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="IMG_8285 2-modified (1).png" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </div>
  )
}
